# Generated by Django 3.0.5 on 2020-12-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('passport', models.TextField(max_length=11)),
                ('oms', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Disease')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Person')),
                ('symptoms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Symptom')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Symptom'),
        ),
    ]
