# Generated by Django 3.0.5 on 2020-12-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(to='project.Symptom'),
        ),
        migrations.RemoveField(
            model_name='examination',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='examination',
            name='symptoms',
            field=models.ManyToManyField(to='project.Symptom'),
        ),
    ]
