# Generated by Django 3.0.5 on 2020-12-28 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201228_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examination',
            name='description',
            field=models.TextField(default='00-00-2020 10:00:00'),
            preserve_default=False,
        ),
    ]
