# Generated by Django 3.0.5 on 2021-01-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20201228_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='disease_id',
        ),
        migrations.AddField(
            model_name='examination',
            name='diseases',
            field=models.ManyToManyField(to='project.Disease'),
        ),
    ]
